name: Sync OAS to ReadMe
on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        
      - name: GitHub Action
        uses: readmeio/rdme@8.0.4
        with:
          rdme: openapi ./Authorization_API_stoplight_studio.yaml --key=${{secrets.README_AUTH_KEY}} --id=611ef791381a5ac89dcc27e5
          
