name: Sync OAS to ReadMe
on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        
      - name: GitHub Action
        uses: readmeio/rdme@8.0.4
        with:
          rdme: openapi Authorization_API.yaml --key=${{ secrets.README_WAREHOUSE_AUTH_KEY }} --id=${{ secrets.README_WAREHOUSE_AUTH_ID }}
          
      - name: GitHub Action
        uses: readmeio/rdme@8.0.4
        with:
          rdme: openapi V1_Code_Info_API.yaml --key=${{ secrets.README_WAREHOUSE_AUTH_KEY }} --id=${{ secrets.README_WAREHOUSE_CODE_INFO_ID }}
        
      - name: GitHub Action
        uses: readmeio/rdme@8.0.4
        with:
          rdme: openapi V1_Orders_API.yaml --key=${{ secrets.README_WAREHOUSE_AUTH_KEY }} --id=${{ secrets.README_WAREHOUSE_ORDERS_ID }}
        
      - name: GitHub Action
        uses: readmeio/rdme@8.0.4
        with:
          rdme: openapi V1_Products_API.yaml --key=${{ secrets.README_WAREHOUSE_AUTH_KEY }} --id=${{ secrets.README_WAREHOUSE_PRODUCTS_ID }}
