name: Sync OAS to ReadMe
on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        
      - name: Sync the warehouse authorization API
        uses: readmeio/rdme@8.0.4
        with:
          rdme: openapi Authorization_API.yaml --key=${{ secrets.README_WAREHOUSE_AUTH_KEY }} --id=${{ secrets.README_WAREHOUSE_AUTH_ID }}
          
      - name: Sync the warehouse code information API
        uses: readmeio/rdme@8.0.4
        with:
          rdme: openapi V1_Code_Info_API.yaml --key=${{ secrets.README_WAREHOUSE_AUTH_KEY }} --id=${{ secrets.README_WAREHOUSE_V1_CODE_INFO_ID }}
        
      - name: Sync the warehouse orders API
        uses: readmeio/rdme@8.0.4
        with:
          rdme: openapi V1_Orders_API.yaml --key=${{ secrets.README_WAREHOUSE_AUTH_KEY }} --id=${{ secrets.README_WAREHOUSE_V1_ORDERS_ID }}
        
      - name: Sync the warehouse products API
        uses: readmeio/rdme@8.0.4
        with:
          rdme: openapi V1_Products_API.yaml --key=${{ secrets.README_WAREHOUSE_AUTH_KEY }} --id=${{ secrets.README_WAREHOUSE_V1_PRODUCTS_ID }}
        
      - name: Sync the warehouse shipping customers API
        uses: readmeio/rdme@8.0.4
        with:
          rdme: openapi V1_Ship_Customers_API.yaml --key=${{ secrets.README_WAREHOUSE_AUTH_KEY }} --id=${{ secrets.README_WAREHOUSE_V1_SHIP_CUSTOMER_ID }}

